export const timeZones = [
  "UTC -11",
  "UTC -10",
  "UTC -9",
  "UTC -8",
  "UTC -7",
  "UTC -6",
  "UTC -5",
  "UTC -4",
  "UTC -3",
  "UTC -2",
  "UTC -1",
  "UTC",
  "UTC +1",
  "UTC +2",
  "UTC +3",
  "UTC +4",
  "UTC +5",
  "UTC +6",
  "UTC +7",
  "UTC +8",
  "UTC +9",
  "UTC +10",
];

export const regions = [
  "Africa",
  "Asia",
  "Australia & Oceania",
  "Central America & Caribbean",
  "Europe",
  "Middle East & North Africa",
  "North America",
  "South America",
];

export const countries = [
  "Australia",
  "Canada",
  "China",
  "Denmark",
  "European Union",
  "Finland",
  "France",
  "Germany",
  "Hong Kong",
  "India",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Republic of Korea",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "United Kingdom",
  "United States",
  "Other",
];

export const experienceLevels = [
  "15 or more years",
  "10-14 years",
  "5-9 years",
  "3-4 years",
  "1-2 years",
  "Less than 1 year",
];

export const accessibilityAreas = [
  "ADA Compliance",
  "Advocacy",
  "Assistive Technology",
  "Augmented Reality",
  "Design",
  "Development",
  "Mobile Applications",
  "Occupational Therapy",
  "Software Applications",
  "Testing",
  "Universal Design",
  "Web Design and Development",
  "Other",
];

export const training = [
  "Professional training course",
  "IAAP Certification Coursework",
  "Self guided study",
  "AccessU",
  "Study Away",
  "University or other formal education",
  "Other",
  "I do not yet know anything about accessibility",
];

export const topics = [
  "Career Development",
  "Design",
  "Development",
  "Preparing for IAAP certification",
  "Testing",
  "Usability",
  "Virtual and augmented reality",
  "Other",
];