name: Prettier Check

on: [ push, pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: astro
    env:
      NODE_ENV: "null"
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      # - name: Change directory  
      #   run: "cd ./astro"
  
      # - name: Install prettier
      #   working-directory: ./astro
      #   run: "npm i prettier"

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_plugins: "prettier-plugin-astro"
          prettier_options: "--check **/*.{js,ts,astro}"
          working_directory: "/home/runner/work/accessiblecommunity.github.io/accessiblecommunity.github.io/astro"